[package]
name = "slint-terminal"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
slint = { version = "=1.17.1", default-features = false, features = [
    "accessibility",
    "backend-winit",
    "compat-1-2",
    "renderer-femtovg-wgpu",
    "std",
    "unstable-wgpu-29",
] }
alacritty_terminal = "0.26.0"
arboard = { version = "3.6.1", default-features = false }
bytemuck = { version = "1.23", features = ["derive"] }
glyphon = "0.11.0"
[build-dependencies]
slint-build = "=1.17.1"
